package: mail_sprog
version: '1.0.2'
author: 'Kreatif'
compile: 0

requires:
    php:
        version: '>=7, <9'
    packages:
        yform_usability: ^1.5.0

page:
    title: Sprog Mail
    perm: mail_sprog[]
    subpages:
        list:
            title: 'translate:mail_wildcard'
            perm: mail_sprog[list]